global:
  nameOverride: "multipaper"
  # Defines the service account for all running instanes
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # When empty the full name of the Helm deployment would be used.
    name: ""

# MultiPaper master server
master:

  # Built-in Proxy settings
  proxy:
    enabled: true
    service:
      # Type can be ClusterIP or NodePort
      type: NodePort

      # Port on which the MultiPaper master proxy server is listening.
      port: 25565
      # Target port to which the proxy service should be mapped to.
      targetPort: 25565
  
  image:
    repository: "multipaper-master"
    # Tag of the Docker image to be used.
    # Defaults to the Chart's app version if left blank.
    tag: "2.8.4"
    pullPolicy: IfNotPresent

  # Configure the Update Strategy Type for the StatefulSet
  # See https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
  updateStrategyType: "RollingUpdate"

  resources: {}
  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 250m
  #   limits:
  #     memory: 256Mi
  #     cpu: 250m

  service:
    # Port on which the MultiPaper master server is listening.
    port: 35353
    # Target port to which the master service should be mapped to
    targetPort: 35353

  # Section for startup, readiness and liveness probes
  probes:

    # Probe used to weed out slow pods
    startupProbe:
      enabled: true
      # When a probe fails, Kubernetes will try failureThreshold times before giving up.
      # After this it will restart the container.
      failureThreshold: 3
      # How often (in seconds) to perform the probe.
      periodSeconds: 1
    
    # Probe used to define whether a pod is ready or not
    readinessProbe:
      enabled: true
      # Number of seconds after the container has started before liveness or readiness probes are initiated.
      initialDelaySeconds: 5
      # How often (in seconds) to perform the probe.
      periodSeconds: 2
      # When a probe fails, Kubernetes will try failureThreshold times before giving up.
      # After this it will mark the Pod as Unready
      failureThreshold: 3
      # Minimum consecutive successes for the probe to be considered successful after having failed.
      successThreshold: 2
      # Number of seconds after which the probe times out and ultimately fails.
      timeoutSeconds: 1

    # Probe used to verify whether a pod is still running succesfully
    livenessProbe:
      enabled: true
      # Number of seconds after the container has started before liveness or readiness probes are initiated.
      initialDelaySeconds: 5
      # How often (in seconds) to perform the probe.
      periodSeconds: 2
      # When a probe fails, Kubernetes will try failureThreshold times before giving up.
      # After this it will restart the container.
      failureThreshold: 3
      # Minimum consecutive successes for the probe to be considered successful after having failed.
      successThreshold: 1
      # Number of seconds after which the probe times out and ultimately fails.
      timeoutSeconds: 1
  
  
  labels: {}

# MultiPaper server
server:
  image:
    repository: "multipaper"
    # Tag of the Docker image to be used.
    # Defaults to the Chart's app version if left blank.
    tag: "1.18.2-65"
    pullPolicy: IfNotPresent

  resources: {}
  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 250m
  #   limits:
  #     memory: 256Mi
  #     cpu: 250m

  service:
    # Port on which the MultiPaper master server is listening.
    port: 25565
    # Target port to which the service should be mapped to.
    targetPort: 25565

  # Section for startup, readiness and liveness probes
  probes:

    # Probe used to weed out slow pods
    startupProbe:
      enabled: true
      # When a probe fails, Kubernetes will try failureThreshold times before giving up.
      # After this it will restart the container.
      failureThreshold: 3
      # How often (in seconds) to perform the probe.
      periodSeconds: 20
    
    # Probe used to define whether a pod is ready or not
    readinessProbe:
      enabled: true
      # Number of seconds after the container has started before liveness or readiness probes are initiated.
      initialDelaySeconds: 40
      # How often (in seconds) to perform the probe.
      periodSeconds: 5
      # When a probe fails, Kubernetes will try failureThreshold times before giving up.
      # After this it will mark the Pod as Unready
      failureThreshold: 5
      # Minimum consecutive successes for the probe to be considered successful after having failed.
      successThreshold: 2
      # Number of seconds after which the probe times out and ultimately fails.
      timeoutSeconds: 1

    # Probe used to verify whether a pod is still running succesfully
    livenessProbe:
      enabled: true
      # Number of seconds after the container has started before liveness or readiness probes are initiated.
      initialDelaySeconds: 40
      # How often (in seconds) to perform the probe.
      periodSeconds: 5
      # When a probe fails, Kubernetes will try failureThreshold times before giving up.
      # After this it will restart the container.
      failureThreshold: 5
      # Minimum consecutive successes for the probe to be considered successful after having failed.
      successThreshold: 1
      # Number of seconds after which the probe times out and ultimately fails.
      timeoutSeconds: 1

  labels: {}