apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "multipaper-helm.fullname" . }}
  labels:
    {{- include "multipaper-helm.server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "multipaper-helm.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "multipaper-helm.server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "multipaper-helm.serviceAccount.name" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.server.uid }}
        runAsGroup: {{ .Values.server.gid }}
        fsGroup: {{ .Values.server.gid }}
      initContainers:
        - name: copy-configuration
          image: remcospigot/multipaper-init:0.0.1
          command: [ "/bin/sh", "-c", "cp /tmp/multipaper/* /multipaper/data && /usr/local/bin/envsubst < /tmp/multipaper/multipaper.yml > /multipaper/data/multipaper.yml" ]
          volumeMounts:
            - name: multipaper-configs
              mountPath: /tmp/multipaper
              readOnly: true
            - name: multipaper-configs-data
              mountPath: /multipaper/data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          command: [ "java", "-jar", "/multipaper/multipaper.jar" ]
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: server
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          {{- if .Values.server.probes.readinessProbe.startupProbe }}
          startupProbe:
            tcpSocket:
              port: server
            failureThreshold: {{ .Values.server.probes.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.server.probes.startupProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.server.probes.readinessProbe.timeoutSecond }}
          readinessProbe:
            tcpSocket:
              port: server
            initialDelaySeconds: {{ .Values.server.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.probes.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.server.probes.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.server.probes.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.server.probes.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.server.probes.livenessProbe.timeoutSecond }}
          livenessProbe:
            tcpSocket:
              port: server
            initialDelaySeconds: {{ .Values.server.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.probes.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.server.probes.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.server.probes.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.server.probes.livenessProbe.timeoutSeconds }}
          {{- end }}
          volumeMounts:
            - name: multipaper-configs-data
              mountPath: /multipaper/data
      volumes:
        - name: multipaper-configs
          projected:
            sources:
              - configMap:
                  name: {{ template "multipaper-helm.fullname" . }}-pufferfish
              - configMap:
                  name: {{ template "multipaper-helm.fullname" . }}-airplane
              - configMap:
                  name: {{ template "multipaper-helm.fullname" . }}-paper
              - configMap:
                  name: {{ template "multipaper-helm.fullname" . }}-spigot
              - configMap:
                  name: {{ template "multipaper-helm.fullname" . }}-bukkit
              - configMap:
                  name: {{ template "multipaper-helm.fullname" . }}-minecraft
              - configMap:
                  name: {{ template "multipaper-helm.fullname" . }}-config
        - name: multipaper-configs-data
          emptyDir: {}