apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "multipaper-helm.fullname" . }}-spigot
  labels:
    {{- include "multipaper-helm.server.labels" . | nindent 4 }}
data:
  eula.txt: |
    #By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
    #You also agree that tacos are tasty, and the best food in the world.
    eula=true
  spigot.yml: | 
    # This is the main configuration file for Spigot.
    # As you can see, there's tons to configure. Some options may impact gameplay, so use
    # with caution, and make sure you know what each option does before configuring.
    # For a reference for any variable inside this file, check out the Spigot wiki at
    # http://www.spigotmc.org/wiki/spigot-configuration/
    #
    # If you need help with the configuration or have any questions related to Spigot,
    # join us at the Discord or drop by our forums and leave a post.
    #
    # Discord: https://www.spigotmc.org/go/discord
    # Forums: http://www.spigotmc.org/

    settings:
      debug: false
      player-shuffle: 0
      user-cache-size: 1000
      moved-wrongly-threshold: 0.0625
      moved-too-quickly-multiplier: 10.0
      timeout-time: 60
      restart-on-crash: true
      restart-script: ./start.sh
      netty-threads: 4
      attribute:
        maxHealth:
          max: 2048.0
        movementSpeed:
          max: 2048.0
        attackDamage:
          max: 2048.0
      log-villager-deaths: true
      log-named-deaths: true
      save-user-cache-on-stop-only: false
      sample-count: 12
      bungeecord: {{ .Values.master.proxy.enabled }}
    commands:
      log: true
      tab-complete: 0
      send-namespaced: true
      spam-exclusions:
      - /skill
      replace-commands:
      - setblock
      - summon
      - testforblock
      - tellraw
      silent-commandblock-console: false
    messages:
      restart: Server is restarting
      whitelist: You are not whitelisted on this server!
      unknown-command: Unknown command. Type "/help" for help.
      server-full: The server is full!
      outdated-client: Outdated client! Please use {0}
      outdated-server: Outdated server! I'm still on {0}
    world-settings:
      default:
        below-zero-generation-in-existing-chunks: true
        verbose: false
        merge-radius:
          exp: 3.0
          item: 2.5
        growth:
          cactus-modifier: 100
          cane-modifier: 100
          melon-modifier: 100
          mushroom-modifier: 100
          pumpkin-modifier: 100
          sapling-modifier: 100
          beetroot-modifier: 100
          carrot-modifier: 100
          potato-modifier: 100
          wheat-modifier: 100
          netherwart-modifier: 100
          vine-modifier: 100
          cocoa-modifier: 100
          bamboo-modifier: 100
          sweetberry-modifier: 100
          kelp-modifier: 100
          twistingvines-modifier: 100
          weepingvines-modifier: 100
          cavevines-modifier: 100
          glowberry-modifier: 100
        entity-activation-range:
          animals: 32
          monsters: 32
          raiders: 48
          misc: 16
          water: 16
          villagers: 32
          flying-monsters: 32
          wake-up-inactive:
            animals-max-per-tick: 4
            animals-every: 1200
            animals-for: 100
            monsters-max-per-tick: 8
            monsters-every: 400
            monsters-for: 100
            villagers-max-per-tick: 4
            villagers-every: 600
            villagers-for: 100
            flying-monsters-max-per-tick: 8
            flying-monsters-every: 200
            flying-monsters-for: 100
          villagers-work-immunity-after: 100
          villagers-work-immunity-for: 20
          villagers-active-for-panic: true
          tick-inactive-villagers: true
          ignore-spectators: false
        entity-tracking-range:
          players: 48
          animals: 48
          monsters: 48
          misc: 32
          other: 64
        ticks-per:
          hopper-transfer: 8
          hopper-check: 1
        hopper-amount: 1
        dragon-death-sound-radius: 0
        seed-village: 10387312
        seed-desert: 14357617
        seed-igloo: 14357618
        seed-jungle: 14357619
        seed-swamp: 14357620
        seed-monument: 10387313
        seed-shipwreck: 165745295
        seed-ocean: 14357621
        seed-outpost: 165745296
        seed-endcity: 10387313
        seed-slime: 987234911
        seed-nether: 30084232
        seed-mansion: 10387319
        seed-fossil: 14357921
        seed-portal: 34222645
        seed-stronghold: default
        hunger:
          jump-walk-exhaustion: 0.05
          jump-sprint-exhaustion: 0.2
          combat-exhaustion: 0.1
          regen-exhaustion: 6.0
          swim-multiplier: 0.01
          sprint-multiplier: 0.1
          other-multiplier: 0.0
        max-tnt-per-tick: 100
        max-tick-time:
          tile: 50
          entity: 50
        end-portal-sound-radius: 0
        mob-spawn-range: 8
        nerf-spawner-mobs: false
        zombie-aggressive-towards-villager: true
        arrow-despawn-rate: 1200
        trident-despawn-rate: 1200
        hanging-tick-frequency: 100
        wither-spawn-sound-radius: 0
        enable-zombie-pigmen-portal-spawns: true
        item-despawn-rate: 6000
        view-distance: default
        simulation-distance: default
        thunder-chance: 100000
    players:
      disable-saving: false
    advancements:
      disable-saving: false
      disabled:
      - minecraft:story/disabled
    config-version: 12
    stats:
      disable-saving: false
      forced-stats: {}
  bukkit.yml: |
    settings:
      allow-end: true
      warn-on-overload: true
      permissions-file: permissions.yml
      update-folder: update
      plugin-profiling: false
      connection-throttle: 4000
      query-plugins: true
      deprecated-verbose: default
      shutdown-message: Server closed
      minimum-api: none
    spawn-limits:
      monsters: 70
      animals: 10
      water-animals: 5
      water-ambient: 20
      water-underground-creature: 5
      axolotls: 5
      ambient: 15
    chunk-gc:
      period-in-ticks: 600
    ticks-per:
      animal-spawns: 400
      monster-spawns: 1
      water-spawns: 1
      water-ambient-spawns: 1
      water-underground-creature-spawns: 1
      axolotl-spawns: 1
      ambient-spawns: 1
      autosave: 6000
    aliases: now-in-commands.yml
  paper.yml: |
    # This is the main configuration file for Paper.
    # As you can see, there's tons to configure. Some options may impact gameplay, so use
    # with caution, and make sure you know what each option does before configuring.
    #
    # If you need help with the configuration or have any questions related to Paper,
    # join us in our Discord or IRC channel.
    #
    # Discord: https://discord.gg/papermc
    # IRC: #paper @ irc.esper.net ( https://webchat.esper.net/?channels=paper ) 
    # Website: https://papermc.io/ 
    # Docs: https://docs.papermc.io/ 

    verbose: false
    messages:
      kick:
        authentication-servers-down: ''
        flying-player: Flying is not enabled on this server
        flying-vehicle: Flying is not enabled on this server
        connection-throttle: Connection throttled! Please wait before reconnecting.
      no-permission: '&cI''m sorry, but you do not have permission to perform this command.
        Please contact the server administrators if you believe that this is in error.'
    timings:
      enabled: true
      really-enabled: false
      verbose: true
      url: https://timings.aikar.co/
      server-name-privacy: false
      hidden-config-entries:
      - database
      - settings.bungeecord-addresses
      - settings.velocity-support.secret
      - web-services.token
      history-interval: 300
      history-length: 3600
      server-name: Unknown Server
    config-version: 27
    settings:
      send-full-pos-for-hard-colliding-entities: true
      suggest-player-names-when-null-tab-completions: true
      chunk-loading:
        min-load-radius: 2
        max-concurrent-sends: 2
        autoconfig-send-distance: true
        target-player-chunk-send-rate: 100.0
        global-max-chunk-send-rate: -1.0
        enable-frustum-priority: false
        global-max-chunk-load-rate: -1.0
        player-max-concurrent-loads: 20.0
        global-max-concurrent-loads: 500.0
        player-max-chunk-load-rate: -1.0
      item-validation:
        display-name: 8192
        loc-name: 8192
        lore-line: 8192
        book:
          title: 8192
          author: 8192
          page: 16384
      watchdog:
        early-warning-every: 5000
        early-warning-delay: 10000
      spam-limiter:
        recipe-spam-increment: 1
        recipe-spam-limit: 20
        tab-spam-increment: 1
        tab-spam-limit: 500
      bungee-online-mode: true
      velocity-support:
        enabled: false
        online-mode: false
        secret: ''
      max-joins-per-tick: 3
      player-auto-save-rate: -1
      max-player-auto-save-per-tick: -1
      console:
        enable-brigadier-highlighting: true
        enable-brigadier-completions: true
      proxy-protocol: false
      log-player-ip-addresses: true
      loggers:
        deobfuscate-stacktraces: true
        use-rgb-for-named-text-colors: true
      book-size:
        page-max: 2560
        total-multiplier: 0.98
      console-has-all-permissions: false
      region-file-cache-size: 256
      enable-player-collisions: true
      save-empty-scoreboard-teams: false
      fix-target-selector-tag-completion: true
      use-alternative-luck-formula: false
      lag-compensate-block-breaking: true
      time-command-affects-all-worlds: false
      incoming-packet-spam-threshold: 300
      load-permissions-yml-before-plugins: true
      use-display-name-in-quit-message: false
      fix-entity-position-desync: true
      track-plugin-scoreboards: false
      use-dimension-type-for-custom-spawners: false
      unsupported-settings:
        allow-permanent-block-break-exploits: false
        perform-username-validation: true
        allow-headless-pistons: false
        allow-piston-duplication: false
        allow-permanent-block-break-exploits-readme: This setting controls if players
          should be able to break bedrock, end portals and other intended to be permanent
          blocks.
        allow-headless-pistons-readme: This setting controls if players should be able
          to create headless pistons.
        allow-piston-duplication-readme: This setting controls if player should be able
          to use TNT duplication, but this also allows duplicating carpet, rails and potentially
          other items
      async-chunks:
        threads: -1
      packet-limiter:
        kick-message: '&cSent too many packets'
        limits:
          all:
            interval: 7.0
            max-packet-rate: 500.0
          PacketPlayInAutoRecipe:
            interval: 4.0
            max-packet-rate: 5.0
            action: DROP
    world-settings:
      default:
        disable-teleportation-suffocation-check: false
        container-update-tick-rate: 1
        armor-stands-do-collision-entity-lookups: true
        skeleton-horse-thunder-spawn-chance: 0.01
        nether-ceiling-void-damage-height: 0
        keep-spawn-loaded: false
        anti-xray:
          enabled: false
          engine-mode: 1
          max-block-height: 64
          update-radius: 2
          lava-obscures: false
          use-permission: false
          hidden-blocks:
          - copper_ore
          - deepslate_copper_ore
          - gold_ore
          - deepslate_gold_ore
          - iron_ore
          - deepslate_iron_ore
          - coal_ore
          - deepslate_coal_ore
          - lapis_ore
          - deepslate_lapis_ore
          - mossy_cobblestone
          - obsidian
          - chest
          - diamond_ore
          - deepslate_diamond_ore
          - redstone_ore
          - deepslate_redstone_ore
          - clay
          - emerald_ore
          - deepslate_emerald_ore
          - ender_chest
          replacement-blocks:
          - stone
          - oak_planks
          - deepslate
        prevent-tnt-from-moving-in-water: false
        game-mechanics:
          disable-relative-projectile-velocity: false
          disable-end-credits: false
          disable-sprint-interruption-on-attack: false
          shield-blocking-delay: 5
          disable-player-crits: false
          disable-pillager-patrols: false
          pillager-patrols:
            spawn-chance: 0.2
            spawn-delay:
              per-player: false
              ticks: 12000
            start:
              per-player: false
              day: 5
          disable-chest-cat-detection: false
          nerf-pigmen-from-nether-portals: false
          disable-mob-spawner-spawn-egg-transformation: false
          disable-unloaded-chunk-enderpearl-exploit: true
          scan-for-legacy-ender-dragon: true
          fix-curing-zombie-villager-discount-exploit: true
        grass-spread-tick-rate: 1
        max-leash-distance: 10.0
        fix-items-merging-through-walls: false
        light-queue-size: 20
        auto-save-interval: -1
        only-players-collide: false
        allow-vehicle-collisions: true
        portal-search-radius: 128
        portal-create-radius: 16
        portal-search-vanilla-dimension-scaling: true
        allow-non-player-entities-on-scoreboards: false
        parrots-are-unaffected-by-player-movement: false
        fix-climbing-bypassing-cramming-rule: false
        disable-explosion-knockback: false
        fixed-chunk-inhabited-time: -1
        disable-ice-and-snow: false
        disable-thunder: false
        keep-spawn-loaded-range: 10
        mob-effects:
          undead-immune-to-certain-effects: true
          spiders-immune-to-poison-effect: true
          immune-to-wither-effect:
            wither: true
            wither-skeleton: true
        phantoms-do-not-spawn-on-creative-players: true
        phantoms-only-attack-insomniacs: true
        water-over-lava-flow-speed: 5
        redstone-implementation: vanilla
        show-sign-click-command-failure-msgs-to-player: false
        per-player-mob-spawns: true
        generator-settings:
          flat-bedrock: false
        non-player-arrow-despawn-rate: -1
        creative-arrow-despawn-rate: -1
        entities-target-with-follow-range: false
        spawner-nerfed-mobs-should-jump: false
        wateranimal-spawn-height:
          maximum: default
          minimum: default
        zombies-target-turtle-eggs: true
        zombie-villager-infection-chance: -1.0
        unsupported-settings:
          fix-invulnerable-end-crystal-exploit: true
        all-chunks-are-slime-chunks: false
        armor-stands-tick: true
        mob-spawner-tick-rate: 1
        iron-golems-can-spawn-in-air: false
        split-overstacked-loot: true
        map-item-frame-cursor-limit: 128
        delay-chunk-unloads-by: 10s
        max-auto-save-chunks-per-tick: 24
        baby-zombie-movement-modifier: 0.5
        prevent-moving-into-unloaded-chunks: false
        count-all-mobs-for-spawning: false
        use-vanilla-world-scoreboard-name-coloring: false
        spawn-limits:
          monster: -1
          creature: -1
          ambient: -1
          axolotls: -1
          underground_water_creature: -1
          water_creature: -1
          water_ambient: -1
        door-breaking-difficulty:
          zombie:
          - HARD
          zombie_villager:
          - HARD
          husk:
          - HARD
          zombified_piglin:
          - HARD
          vindicator:
          - NORMAL
          - HARD
        wandering-trader:
          spawn-minute-length: 1200
          spawn-day-length: 24000
          spawn-chance-failure-increment: 25
          spawn-chance-min: 25
          spawn-chance-max: 75
        filter-nbt-data-from-spawn-eggs-and-related: true
        disable-creeper-lingering-effect: false
        duplicate-uuid-resolver: saferegen
        duplicate-uuid-saferegen-delete-range: 32
        mobs-can-always-pick-up-loot:
          zombies: false
          skeletons: false
        update-pathfinding-on-block-update: true
        anticheat:
          obfuscation:
            items:
              hide-itemmeta: false
              hide-durability: false
        allow-player-cramming-damage: false
        map-item-frame-cursor-update-interval: 10
        hopper:
          cooldown-when-full: true
          disable-move-event: false
          ignore-occluding-blocks: false
        monster-spawn-max-light-level: -1
        enable-treasure-maps: true
        treasure-maps-return-already-discovered: false
        max-entity-collisions: 8
        frosted-ice:
          enabled: true
          delay:
            min: 20
            max: 40
        lootables:
          auto-replenish: false
          restrict-player-reloot: true
          reset-seed-on-fill: true
          max-refills: -1
          refresh-min: 12h
          refresh-max: 2d
        piglins-guard-chests: true
        experience-merge-max-value: -1
        should-remove-dragon: false
        optimize-explosions: false
        fishing-time-range:
          MinimumTicks: 100
          MaximumTicks: 600
        max-growth-height:
          cactus: 3
          reeds: 3
          bamboo:
            max: 16
            min: 11
        despawn-ranges:
          monster:
            soft: 32
            hard: 128
          creature:
            soft: 32
            hard: 128
          ambient:
            soft: 32
            hard: 128
          axolotls:
            soft: 32
            hard: 128
          underground_water_creature:
            soft: 32
            hard: 128
          water_creature:
            soft: 32
            hard: 128
          water_ambient:
            soft: 32
            hard: 64
          misc:
            soft: 32
            hard: 128
        falling-block-height-nerf: 0
        tnt-entity-height-nerf: 0
        slime-spawn-height:
          swamp-biome:
            maximum: 70.0
            minimum: 50.0
          slime-chunk:
            maximum: 40.0
        allow-using-signs-inside-spawn-protection: false
        ender-dragons-death-always-places-dragon-egg: false
        feature-seeds:
          generate-random-seeds-for-all: false
        tick-rates:
          sensor:
            villager:
              secondarypoisensor: 40
          behavior:
            villager:
              validatenearbypoi: -1
        entity-per-chunk-save-limit:
          experience_orb: -1
          snowball: -1
          ender_pearl: -1
          arrow: -1
          fireball: -1
          small_fireball: -1
        alt-item-despawn-rate:
          enabled: false
          items:
            cobblestone: 300
