{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "multipaper-helm.serviceAccount.name" . }}
  labels:
    {{- include "multipaper-helm.server.labels" . | nindent 4 }}
{{- end -}}