apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "multipaper-helm.fullname" . }}-config
  labels:
    {{- include "multipaper-helm.server.labels" . | nindent 4 }}
data:
  multipaper.yml: |
    # This is the main configuration file for MultiPaper.
    # There's quite alot to configure. Read the docs for more information.
    #
    # Docs: https://github.com/PureGero/MultiPaper/blob/main/MULTIPAPER_YAML.md

    useLocalPlayerCountForServerIsFullKick: false
    {{- if .Values.velocity.enabled }}
    multipaperMasterAddress: {{ template "multipaper-helm.fullname" . }}-velocity-master:{{ .Values.velocity.master.service.targetPort }}
    {{- else }}
    multipaperMasterAddress: {{ template "multipaper-helm.fullname" . }}-master:{{ .Values.master.service.targetPort }}
    {{- end }}
    advertiseToBuiltInProxy: {{ .Values.velocity.enabled }}
    filesToSyncOnStartup:
    filesToSyncInRealTime:
    filesToOnlyUploadOnServerStop:
    ticksPerInactiveEntityTracking: 1
    interServerCompressionThreshold: 0
    interServerConsolidationDelay: 0
    syncScoreboards: true
    logFileSyncing: false
    syncJsonFiles: false
    filesToNotSync:
    - plugins/bStats
    {{- if .Values.velocity.enabled }}
    bungeecordName: $HOSTNAME
    {{- else }}
    bungeecordName: {{ template "multipaper-helm.fullname" . }}
    {{- end }}
