apiVersion: v1
kind: Service
metadata:
  name: {{ template "multipaper-helm.fullname" . }}
  labels:
    {{- include "multipaper-helm.server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: server
  selector:
    {{- include "multipaper-helm.server.selectorLabels" . | nindent 4 }}